### ISSUE TITLE
Tooltips in module JEM Calendar not formatted, after changing month-->old tooltip

### ISSUE THREAD

**Issue by Heklaterriol** [Heklaterriol/JEM-Project#77] opened 2023-02-11 23:21 UTC
see  JEM 4 version
![jem-cal-mod-j4](https://user-images.githubusercontent.com/28540581/218285251-e1bfc057-6b0f-4610-9f85-0e9e575da3c4.png)
and compare with well formatted JEM 2.3.5 (Joomla 3 version)
![jem-cal-mod-j3](https://user-images.githubusercontent.com/28540581/218285267-c9c48e0c-22d1-484d-a90d-f0423cc4db8b.png)

**Comment by jojo12** [comment] 2023-02-15 12:39
2.3.8 something changed, but not yet fixed!

**Comment by Heklaterriol** [comment] 2023-02-15 12:46
Yes, this version here (2.3.8) came before I feedbacked it to the coder – that's why I labelled it to "[fixing in round 4 (2.3.8)"

**Comment by golfy3154** [comment] 2023-02-28 15:54
in version 3.2.9, you have to refresh each time the page when you navigate in calendar module to see the tooltip well-formated

**Comment by golfy3154** [comment] 2023-02-28 16:05
I mean in test version 2.3.9

**Comment by golfy3154** [comment] 2023-02-28 16:13
Ok

Envoyé de mon iPhone

**Comment by golfy3154** [comment] 2023-03-01 07:35
I don't understand why you closed this issue, because I downloaded again and reinstalled test version 3.2.9 and the problem did not disappear

**Comment by jojo12** [comment] 2023-03-01 08:19
@golfy3154: A question to you: **Did you try it on a clean Joomla!4.2.8 only with JEM 2.3.9 in cassiopeia?.**
I have to admit, I first tried on my normal system and then I had this problem too! But then I tried on a clean Joomla! and the problem is away. There must be an interference with something other. And we can't test it with all variations.

**Comment by golfy3154** [comment] 2023-03-01 08:48
I reinstalled jem 2.3.9 on a clean J4.2.8 site and it’s OK. I'm going to do some cleaning on my other test site

Thanks

 

 

De : jojo12 ***@***.***> 
Envoyé : mercredi 1 mars 2023 09:20
À : Heklaterriol/JEM-Project ***@***.***>
Cc : golfy3154 ***@***.***>; Mention ***@***.***>
Objet : Re: [Heklaterriol/JEM-Project] Tooltips in module JEM Calendar not formatted, after changing month-->old tooltip (Issue #77)

 

@golfy3154 <https://github.com/golfy3154> : A question to you: Did you try it on a clean Joomla!4.2.8 only with JEM 2.3.9 in cassiopeia?.
I have to admit, I first tried on my normal system and then I had this problem too! But then I tried on a clean Joomla! and the problem is away. There must be an interference with something other. And we can't test it with all variations.

**Comment by jojo12** [comment] 2023-03-02 07:59
sometimes this comes back, only after a refresh is well formatted tooltip back

**Closed** 2023-03-19 09:29 UTC
